shfmt

diff --git a/files/home/.local/bin/subl b/files/home/.local/bin/subl
--- a/files/home/.local/bin/subl
+++ b/files/home/.local/bin/subl
@@ -2,14 +2,14 @@
 set -e
 
 if [ "$(uname -s)" = "Darwin" ]; then
-    SUBL="/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl"
+	SUBL="/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl"
 else
-    SUBL="/usr/local/bin/subl"
+	SUBL="/usr/local/bin/subl"
 fi
 
 [ -x "$SUBL" ] || {
-    echo "subl not found at $SUBL" >&2
-    exit 1
+	echo "subl not found at $SUBL" >&2
+	exit 1
 }
 
 exec "$SUBL" "$@"
